<?php

/**
 * openFenix Error Layout
 *  
 * @author Joe Nilson
 * @version 1
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype ()?>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php
		echo $this->headTitle ();
		echo $this->headScript ();
		echo $this->headStyle ();
		?>
	</head>

<body style="font-family: Arial; margin: 0px;">
<h1 style="background-color: #cd0000; color: white;"><?php
echo $this->placeholder ( 'title' )?></h1>
		<div style="width: 80%; border: 1px; background-color: #CECECE; margin-left: 100px;">
		<img src='images/default/gtk-dialog-warning.png' align="right">
		<?php
		echo $this->layout ()->content?>
		</div>
		<br />
<br />
</body>

</html>
