<?php

/**
 * openFenix Main Layout
 *  
 * @author Joe Nilson
 * @version 1
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype ()?>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<?php
	echo $this->headTitle ();
	echo $this->headScript ();
	echo $this->headStyle ();
	echo $this->headLink ();
	?>
	<script>
	Ext.SSL_SECURE_URL="scripts/ext/resources/images/default/s.gif";
    Ext.BLANK_IMAGE_URL="scripts/ext/resources/images/default/s.gif";
	Ext.onReady(function(){
		var clock = new Ext.Toolbar.TextItem('');
		var clock2 = new Ext.Toolbar.TextItem('Hoy es: '+new Date().format('d-m-Y'));
		/* This file is created or modified with 
		 * Ext.ux.guid.plugin.GuiDesigner (v2.1.0) 
		 */
		var tabs = new Ext.TabPanel({
            region:'center',
            deferredRender:false,
            activeTab:0,
            items:[{
                //contentEl:'center1',
                title: 'Panel de Informacion',
                html: 'Hola Mundo',
                autoScroll:true
            }]
        });
		 
		var viewport = new Ext.Viewport(
			{
			layout : "border",
			items : [    tabs,    {
			    	region : "north",
			    	height:20
			    //title : "Head Stream"
			},    {
			region : "south",
			split:true,
            height: 25,
            minSize: 25,
            maxSize: 25,
            collapsible: false,
            //title:'Mensajes del Sistema',
            margins:'0 0 0 0',
				//title : "Footer Stream",
				bbar:new Ext.StatusBar({
                    id: 'word-status',
                    //ctCls: 'x-status-text-panel',
                    // These are just the standard toolbar TextItems we created above.  They get
                    // custom classes below in the render handler which is what gives them their
                    // customized inset appearance.
                    items: [clock2,' ',clock, ' ']
                }),
				listeners: {
		            'render': {
		                fn: function(){
		                    // Add a class to the parent TD of each text item so we can give them
		                    // some custom inset box styling:
		                    Ext.fly(clock.getEl().parentNode).addClass('x-status-text-panel');
		                    Ext.fly(clock2.getEl().parentNode).addClass('x-status-text-panel');
		                    // Kick off the clock timer that updates the clock el every second:
							Ext.TaskMgr.start({
							    run: function(){
							        Ext.fly(clock.getEl()).update(new Date().format('g:i:s A'));
							    },
							    interval: 1000
							});
						}
					}
				}
			},    {
			      region : "west",
			      //title : "Menu Stream",
			      collapsible : true
			  }]
		})
	});
	</script>
</head>

<body style="font-family: Arial; margin: 0px;">
<h1 style="background-color: #669933; color: yellow;">
<?php
echo $this->placeholder ( 'title' )?>
</h1>
		<?php
		echo $this->layout ()->content?>

		<br />
		<?php
		echo $this->placeholder ( 'opciones' )?>
<br />
</body>

</html>