<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->escape($this->pageTitle); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/scripts/extjs/resources/css/ext-all.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/scripts/extjs/resources/css/xtheme-olive.css" />
	<style>
	.settings {
        background-image:url(<?php echo $this->baseUrl(); ?>/images/folder_wrench.png);
    }
    .nav {
        background-image:url(<?php echo $this->baseUrl(); ?>/images/folder_go.png);
    }
	</style>	
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/extjs/adapter/ext/ext-base.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/extjs/ext-all.js"></script>
    <script type="text/javascript">
    Ext.onReady(function(){
		var clock = new Ext.Toolbar.TextItem('');
		var clock2 = new Ext.Toolbar.TextItem('Hoy es: '+new Date().format('d-m-Y'));
        Ext.state.Manager.setProvider(new Ext.state.CookieProvider());
        
       var viewport = new Ext.Viewport({
            layout:'border',
            items:[
                new Ext.BoxComponent({ // raw
                    region:'north',
                    el: 'north',
                    height:32
                }),{
                    region:'south',
                    //contentEl: 'south',
                    split:true,
                    height: 25,
                    minSize: 25,
                    maxSize: 25,
                    collapsible: false,
                    //title:'Mensajes del Sistema',
                    margins:'0 0 0 0',
                    bbar:new Ext.StatusBar({
				            id: 'word-status',
				            //ctCls: 'x-status-text-panel',
				            // These are just the standard toolbar TextItems we created above.  They get
				            // custom classes below in the render handler which is what gives them their
				            // customized inset appearance.
				            items: [clock2,' ',clock, ' '
					        ]
				        }),
                    listeners: {
			            'render': {
			                fn: function(){
			                    // Add a class to the parent TD of each text item so we can give them
			                    // some custom inset box styling:
			                    Ext.fly(clock.getEl().parentNode).addClass('x-status-text-panel');
			                    Ext.fly(clock2.getEl().parentNode).addClass('x-status-text-panel');
			                    // Kick off the clock timer that updates the clock el every second:
							    Ext.TaskMgr.start({
							        run: function(){
							            Ext.fly(clock.getEl()).update(new Date().format('g:i:s A'));
							        },
							        interval: 1000
							    });
			                }
			            }
			        }
                           
                }, {
                    region:'east',
                    title: 'Panel Auxiliar',
                    collapsible: true,
                    split:true,
                    width: 225,
                    minSize: 175,
                    maxSize: 400,
                    layout:'fit',
                    margins:'0 5 0 0',
                    items:
                        new Ext.TabPanel({
                            border:false,
                            activeTab:1,
                            tabPosition:'bottom',
                            items:[{
                                html:'<p>A TabPanel component can be a region.</p>',
                                title: 'A Tab',
                                autoScroll:true
                            },
                            new Ext.grid.PropertyGrid({
                                title: 'Property Grid',
                                closable: true,
                                source: {
                                    "(name)": "Properties Grid",
                                    "grouping": false,
                                    "autoFitColumns": true,
                                    "productionQuality": false,
                                    "created": new Date(Date.parse('10/15/2006')),
                                    "tested": false,
                                    "version": .01,
                                    "borderWidth": 1
                                }
                            })]
                        })
                 },{
                    region:'west',
                    id:'west-panel',
                    title:'Panel de Control',
                    split:true,
                    width: 200,
                    minSize: 175,
                    maxSize: 400,
                    collapsible: true,
                    margins:'0 0 0 5',
                    layout:'accordion',
                    layoutConfig:{
                        animate:true
                    },
                    items: [{
                        contentEl: 'west',
                        title:'Menu',
                        border:false,
                        iconCls:'nav'
                    },{
                        title:'Configuracion',
                        html:'<p>Some settings in here.</p>',
                        border:false,
                        iconCls:'settings'
                    }]
                },
                new Ext.TabPanel({
                    region:'center',
                    deferredRender:false,
                    activeTab:0,
                    items:[{
                        contentEl:'center1',
                        title: 'Panel de Informacion',
                        closable:true,
                        autoScroll:true
                    },{
                        contentEl:'center2',
                        title: 'Center Panel',
                        autoScroll:true
                    }]
                })
             ]
        });
        Ext.get("hideit").on('click', function() {
           var w = Ext.getCmp('west-panel');
           w.collapsed ? w.expand() : w.collapse(); 
        });
    });
	</script>
</head>
<body>
    <div id="content">
        <?php echo $this->layout()->content ?>
    </div>
  <div id="west">
    <p>Hi. I'm the west panel.</p>
  </div>
  <div id="north">
    <p>north - generally for menus, toolbars and/or advertisements</p>
  </div>
  <div id="center2">
	<a id="hideit" href="#">Toggle the west region</a>
	Centro 1
  </div>
  <div id="center1">
	Centro 2
  </div>
  <div id="props-panel" style="width:200px;height:200px;overflow:hidden;">
  </div>
  <div id="word-proc"></div>
</body>
</html>
