<?php

/**
 * Default home page view
 *  
 * @author Joe Nilson
 * @version 1
 */

$this->headTitle ( 'New openFenix Project' );
$this->headScript('FILE','scripts/extjs/adapter/ext/ext-base.js');
$this->headScript('FILE','scripts/extjs/ext-all.js');
$this->headLink()->appendStylesheet('scripts/extjs/resources/css/ext-all.css');
$this->headLink()->appendStylesheet('scripts/extjs/resources/css/xtheme-olive.css');
//$this->placeholder ( 'title' )->set ( 'Welcome' );
?>
